"""Render docs/hooks.md from the orchestrator hook registry (harness-tm8t).

Source of truth: `HOOK_SHAPES` (in `src/harness/orchestrator/hooks.py`)
+ the pipeline structure returned by `default_hook_pipeline()` with all
opt-in catchers enabled. The pipeline order is the canonical phase
ordering — first-match semantics depend on it, so the docs follow the
same ordering instead of grouping alphabetically.

Modes:
  --write (default)
    Generate / overwrite docs/hooks.md.

  --check
    Generate to a buffer and compare against docs/hooks.md on disk.
    Exits non-zero if they differ. Used by the registry-coverage test
    so a new hook added without updating the docs surfaces in CI.

The opt-in catchers list mirrors `_OPT_IN_CATCHERS` in hooks.py — adding
a new opt-in catcher there should also add it to `ALL_CATCHERS` below
or its absence will show in `--check` failures.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from harness.orchestrator.hooks import (
    HOOK_SHAPES,
    CatcherDoc,
    default_hook_pipeline,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_PATH = REPO_ROOT / "docs" / "hooks.md"

# Every opt-in catcher we want represented in the rendered docs. Mirrors
# `_OPT_IN_CATCHERS` in hooks.py — keep in sync. The default pipeline
# omits these unless a character opts in via core.yaml, so we feed them
# explicitly here to enumerate the full surface.
ALL_CATCHERS: tuple[str, ...] = (
    "ab_fabrication",
    "ambiguous_context",
    "scope_redirect",
    "reserved_squawk_code",
    "fetch_url_guard",
    "assemble_context_once",
    "opinion_no_trigger",
    "post_search_grounding",
    "post_research_persist",
    "persist_body_citations",
    "source_count_inflation",
)


def render(docs: tuple[CatcherDoc, ...]) -> str:
    """Render the registry as a single markdown file: H2 per phase, a
    table per phase listing (name, shape). Phase order matches the
    pipeline's first-match dispatch order."""
    lines = [
        "# Fabrication-catcher hook registry",
        "",
        "_Generated by `scripts/gen_hook_docs.py` from "
        "`src/harness/orchestrator/hooks.py:HOOK_SHAPES` and the default "
        "hook pipeline with all opt-in catchers enabled. Do not hand-edit; "
        "edit the source registry and re-run the generator._",
        "",
        "Hooks dispatch in the order shown within each phase — first-match "
        "semantics, so a reply that trips two catchers gets the FIRST one's "
        "nudge. Phase ordering: `post_model` → `bail` → `pre_tool` → "
        "`post_tool` → `finalize`.",
        "",
    ]
    # Group by phase, preserving the in-pipeline order within each phase.
    by_phase: dict[str, list[CatcherDoc]] = {}
    for doc in docs:
        by_phase.setdefault(doc.phase, []).append(doc)
    for phase in ("post_model", "bail", "pre_tool", "post_tool", "finalize"):
        phase_docs = by_phase.get(phase, [])
        lines.append(f"## `{phase}`")
        lines.append("")
        if not phase_docs:
            lines.append("_No hooks registered in this phase._")
            lines.append("")
            continue
        lines.append("| Name | Shape |")
        lines.append("| --- | --- |")
        for doc in phase_docs:
            shape = doc.shape.replace("|", r"\|")
            lines.append(f"| `{doc.name}` | {shape} |")
        lines.append("")
    return "\n".join(lines)


def build_docs() -> str:
    """Build the full doc text. Reuses the default pipeline with every
    opt-in catcher enabled so the registered surface matches the docs."""
    pipeline = default_hook_pipeline(catchers=ALL_CATCHERS)
    return render(pipeline.describe())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare against docs/hooks.md instead of writing; exit non-zero on drift.",
    )
    args = parser.parse_args()

    expected = build_docs()
    if args.check:
        if not DOCS_PATH.exists():
            print(f"FAIL: {DOCS_PATH} does not exist", file=sys.stderr)
            return 1
        actual = DOCS_PATH.read_text()
        if actual.rstrip() != expected.rstrip():
            print(
                f"FAIL: {DOCS_PATH} is out of date. Run "
                "`uv run python scripts/gen_hook_docs.py` to regenerate.",
                file=sys.stderr,
            )
            return 1
        return 0
    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.write_text(expected + "\n")
    print(f"Wrote {DOCS_PATH}")
    # Sanity check — every catcher in HOOK_SHAPES should also appear
    # in the rendered docs. Surfaces drift between the shapes registry
    # and the pipeline's actual roster.
    pipeline = default_hook_pipeline(catchers=ALL_CATCHERS)
    rendered_names = {doc.name for doc in pipeline.describe()}
    unrendered = sorted(set(HOOK_SHAPES) - rendered_names)
    if unrendered:
        print(
            f"NOTE: HOOK_SHAPES entries not in default pipeline + ALL_CATCHERS: "
            f"{unrendered}. Add them to ALL_CATCHERS if they're opt-in catchers, "
            f"or drop them from HOOK_SHAPES if they're no longer registered.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
