#!/usr/bin/env bash
# Swap the running vLLM container to a new variant for harness-u70v
# tuning. Reads the existing container's volumes / env / GPU access /
# port mapping via `docker inspect`, stops it, starts a new container
# with the same plumbing but a new model + flags.
#
# Designed to be reversible: prints the prior `docker run`
# equivalent to /tmp/gx10_swap_prior_cmd.sh before stopping anything,
# so the original config can be restored with one command.
#
# Usage:
#   bash gx10_swap_variant.sh flashinfer
#   bash gx10_swap_variant.sh 14b
#   bash gx10_swap_variant.sh 7b
#   bash gx10_swap_variant.sh restore   # re-apply the saved prior config

set -euo pipefail

VARIANT="${1:-}"
NAME="vllm-harness"
IMAGE="vllm/vllm-openai:latest"
PRIOR_CMD_FILE="/tmp/gx10_swap_prior_cmd.sh"

if [ -z "$VARIANT" ]; then
    echo "usage: $0 {flashinfer|14b|7b|restore}"
    exit 1
fi

# --- Discover the currently-running vllm container, then read its
#     run-config so we can replicate volumes + GPU + ports + env.
CID=$(docker ps --filter "ancestor=$IMAGE" --format '{{.ID}}' | head -1)
if [ -z "${CID:-}" ]; then
    CID=$(docker ps --filter "name=vllm" --format '{{.ID}}' | head -1)
fi

if [ "$VARIANT" = "restore" ]; then
    if [ ! -r "$PRIOR_CMD_FILE" ]; then
        echo "no prior-config snapshot at $PRIOR_CMD_FILE"
        exit 1
    fi
    [ -n "${CID:-}" ] && docker stop "$CID" || true
    [ -n "${CID:-}" ] && docker rm "$CID" || true
    bash "$PRIOR_CMD_FILE"
    exit 0
fi

if [ -z "${CID:-}" ]; then
    echo "ERROR: no running vllm container found to inspect"
    exit 1
fi

# Pull volumes (bind + named), GPU device requests, port mapping, env.
MOUNTS=$(docker inspect "$CID" --format '{{range .Mounts}}-v {{.Source}}:{{.Destination}} {{end}}')
PORTS=$(docker inspect "$CID" --format '{{range $p, $bindings := .NetworkSettings.Ports}}{{range $bindings}}-p {{.HostPort}}:{{$p}} {{end}}{{end}}' | sed 's#/tcp##g')
ENVS=$(docker inspect "$CID" --format '{{range .Config.Env}}{{println .}}{{end}}' | grep -v '^PATH=' | grep -v '^HOME=' | grep -v '^HOSTNAME=' | grep -v '^LD_' | sed 's/^/-e /' | tr '\n' ' ')
GPUS=$(docker inspect "$CID" --format '{{range .HostConfig.DeviceRequests}}--gpus {{if eq (len .DeviceIDs) 0}}all{{else}}"device={{range .DeviceIDs}}{{.}},{{end}}"{{end}} {{end}}')
IPC=$(docker inspect "$CID" --format '{{if eq .HostConfig.IpcMode "host"}}--ipc=host{{end}}')
SHM=$(docker inspect "$CID" --format '{{if gt .HostConfig.ShmSize 0}}--shm-size={{.HostConfig.ShmSize}}{{end}}')
PRIOR_ARGS=$(docker inspect "$CID" --format '{{range .Args}}{{.}} {{end}}')

# Save the prior config as a re-runnable script BEFORE stopping anything.
cat > "$PRIOR_CMD_FILE" <<EOF
#!/usr/bin/env bash
# Auto-generated by gx10_swap_variant.sh on $(date -Iseconds).
# Re-runs the docker container that was previously serving vLLM.
docker run -d --name $NAME-restored \\
    $GPUS $IPC $SHM \\
    $MOUNTS \\
    $PORTS \\
    $ENVS \\
    $IMAGE \\
    $PRIOR_ARGS
EOF
chmod +x "$PRIOR_CMD_FILE"
echo "saved prior config: $PRIOR_CMD_FILE"

# --- Pick the new args per variant.
case "$VARIANT" in
    flashinfer)
        MODEL="Qwen/Qwen2.5-Coder-32B-Instruct-AWQ"
        EXTRA_ENV="-e VLLM_ATTENTION_BACKEND=FLASHINFER"
        EXTRA_ARGS="--flashinfer-autotune"
        QUANT="awq_marlin"
        ;;
    14b)
        MODEL="Qwen/Qwen2.5-Coder-14B-Instruct-AWQ"
        EXTRA_ENV=""
        EXTRA_ARGS=""
        QUANT="awq_marlin"
        ;;
    7b)
        MODEL="Qwen/Qwen2.5-Coder-7B-Instruct-AWQ"
        EXTRA_ENV=""
        EXTRA_ARGS=""
        QUANT="awq_marlin"
        ;;
    *)
        echo "unknown variant: $VARIANT  (expected flashinfer|14b|7b|restore)"
        exit 2
        ;;
esac

NEW_NAME="vllm-harness-$VARIANT"
echo "stopping current container ($CID)..."
docker stop "$CID"
docker rm "$CID" || true

echo "starting variant=$VARIANT model=$MODEL ..."
# shellcheck disable=SC2086  # we want word-splitting on the option groups
docker run -d --name "$NEW_NAME" \
    $GPUS $IPC $SHM \
    $MOUNTS \
    $PORTS \
    $ENVS $EXTRA_ENV \
    "$IMAGE" \
    --model "$MODEL" \
    --quantization "$QUANT" \
    --max-model-len 32768 \
    --enable-auto-tool-choice --tool-call-parser hermes \
    --host 0.0.0.0 \
    $EXTRA_ARGS

# --- Wait for ready by polling /health until 200.
NEW_CID=$(docker ps --filter "name=$NEW_NAME" --format '{{.ID}}' | head -1)
echo "new container: $NEW_CID — waiting for /health=200..."
deadline=$(( $(date +%s) + 600 ))
while [ "$(date +%s)" -lt "$deadline" ]; do
    if curl -sf --max-time 3 http://127.0.0.1:8000/health >/dev/null 2>&1; then
        echo "READY at $(date -Iseconds)"
        break
    fi
    sleep 5
done

# Print the engine-init banner so we can see which kernels got picked
# for this variant.
echo
echo "=== engine init (key lines) ==="
docker logs "$NEW_CID" 2>&1 | grep -iE \
    "version 0|quantization|awq|marlin|attention backend|FlashAttention|FlashInfer|enforce.eager|CUDA graph|KV cache size|model loading took|Asynchronous scheduling" \
    | head -30
echo
echo "Run the probe from the Mac to score this variant:"
echo "  uv run python scripts/bench_vllm_remote.py"
echo
echo "Restore prior config when done:  bash $0 restore"
